lib/matched_web/router.ex
defmodule MatchedWeb.Router do
  use MatchedWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug MatchedWeb.LocalePlug
  end

  #  pipeline :api do
  #    plug :accepts, ["json"]
  #  end

  scope "/", MatchedWeb do
    pipe_through :browser

    get "/judges", JudgeController, :index
    get "/judges/:id", JudgeController, :show
    get "/projects", ProjectController, :index
    get "/projects/:id", ProjectController, :show
    get "/", PageController, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", MatchedWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: MatchedWeb.Telemetry
    end
  end
end

lib/matched/application.ex
defmodule Matched.Application do
  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  @moduledoc false

  use Application

  def start(_type, _args) do
    children = [
      # Start the Ecto repository
      Matched.Repo,
      # Start the Telemetry supervisor
      MatchedWeb.Telemetry,
      # Start the PubSub system
      {Phoenix.PubSub, name: Matched.PubSub},
      # Start the Endpoint (http/https)
      MatchedWeb.Endpoint
      # Start a worker by calling: Matched.Worker.start_link(arg)
      # {Matched.Worker, arg}
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: Matched.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  def config_change(changed, _new, removed) do
    MatchedWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

lib/matched/panels.ex
defmodule Matched.Panels do
  @moduledoc """
  The Panels context.
  """

  alias Matched.Panels.Judge

  def list_judges do
    [
      %Judge{id: "1", name: "Laura Castro", availability: false, concentration: "ES"},
      %Judge{id: "2", name: "Beatriz Pérez", availability: true, concentration: "C"},
      %Judge{id: "3", name: "María Martínez", availability: false, concentration: "TI"},
      %Judge{id: "4", name: "Susana Ladra", availability: true, concentration: "SI"},
      %Judge{id: "5", name: "Adriana Dapena", availability: true, concentration: "EC"}
    ]
  end

  def get_judge(id) do
    Enum.find(list_judges(), fn map -> map.id == id end)
  end

  def get_judge_by(params) do
    Enum.find(list_judges(), fn map ->
      Enum.all?(params, fn {key, val} -> Map.get(map, key) == val end)
    end)
  end
end

lib/matched/panels/judge.ex
defmodule Matched.Panels.Judge do
  @moduledoc """
  Defines the data structure for representing a judge.
  """
  # other traits of interest: sex, served, group
  defstruct [:id, :name, :availability, :concentration]
end

lib/matched/projects.ex
defmodule Matched.Projects do
  @moduledoc """
  The Projects context.
  """

  alias Matched.Projects.Project

  def list_projects do
    [
      %Project{
        id: "1",
        title: "A very efficient ML-based compiler",
        student: "Grace Hopper",
        concentration: "C"
      },
      %Project{
        id: "2",
        title: "A large-scale Big Data distributed analyzer",
        student: "Annette Bieniusa",
        concentration: "SI"
      },
      %Project{
        id: "3",
        title: "An IoT-oriented security architecture",
        student: "Katie Moussouris",
        concentration: "EC"
      },
      %Project{
        id: "4",
        title: "A web-based integration of tests-as-infrastructure",
        student: "Huiqing Li",
        concentration: "TI"
      },
      %Project{
        id: "5",
        title: "A space-first methodology for requirements elicitation",
        student: "Margaret Hamilton",
        concentration: "ES"
      }
    ]
  end

  def get_project(id) do
    Enum.find(list_projects(), fn map -> map.id == id end)
  end

  def get_project_by(params) do
    Enum.find(list_projects(), fn map ->
      Enum.all?(params, fn {key, val} -> Map.get(map, key) == val end)
    end)
  end
end

lib/matched/projects/project.ex
defmodule Matched.Projects.Project do
  @moduledoc """
  Defines the data structure for representing a project.
  """
  # other traits of interest: tutor
  defstruct [:id, :title, :student, :concentration]
end

lib/matched/repo.ex
defmodule Matched.Repo do
  use Ecto.Repo,
    otp_app: :matched,
    adapter: Ecto.Adapters.Postgres
end

lib/matched_web/controllers/judge_controller.ex
defmodule MatchedWeb.JudgeController do
  use MatchedWeb, :controller

  alias Matched.Panels

  def index(conn, _params) do
    render(conn, "index.html", judges: Panels.list_judges())
  end

  def show(conn, %{"id" => id}) do
    render(conn, "show.html", judge: Panels.get_judge(id))
  end
end

lib/matched_web/controllers/page_controller.ex
defmodule MatchedWeb.PageController do
  use MatchedWeb, :controller

  def index(conn, _params) do
    render(conn, "index.html")
  end
end

lib/matched_web/controllers/project_controller.ex
defmodule MatchedWeb.ProjectController do
  use MatchedWeb, :controller

  alias Matched.Projects

  def index(conn, _params) do
    render(conn, "index.html", projects: Projects.list_projects())
  end

  def show(conn, %{"id" => id}) do
    render(conn, "show.html", project: Projects.get_project(id))
  end
end

lib/matched_web/views/error_view.ex
defmodule MatchedWeb.ErrorView do
  use MatchedWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

lib/matched_web/views/judge_view.ex
defmodule MatchedWeb.JudgeView do
  use MatchedWeb, :view
end

lib/matched_web/views/layout_view.ex
defmodule MatchedWeb.LayoutView do
  use MatchedWeb, :view
end

lib/matched_web/views/page_view.ex
defmodule MatchedWeb.PageView do
  use MatchedWeb, :view
end

lib/matched_web/views/project_view.ex
defmodule MatchedWeb.ProjectView do
  use MatchedWeb, :view
end

lib/matched_web/templates/judge/index.html.eex
<h1><%= gettext("Listing judges") %></h1>

<table>
  <%= for judge <- @judges do %>
  <tr>
    <td style="text-align: right"><%= render "judge.html", judge: judge %></td>
    <td style="text-align: left"><%= button gettext("View"), to: Routes.judge_path(@conn, :show, judge.id), method: :get%></td>
  </tr>
  <% end %>
</table>

lib/matched_web/templates/judge/judge.html.eex
<%= if @judge.availability do %>
    <b><%= @judge.name %></b>
<% else %>
    <i><%= @judge.name %></i>
<% end %>

lib/matched_web/templates/judge/show.html.eex
<h1><%= gettext("Showing judge details") %></h1>
<div style="text-align: center">
<%= render "judge.html", judge: @judge %><%= gettext("to avaliate") %>: <%= @judge.concentration %>
</div>

lib/matched_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="gl">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Matched · Phoenix Framework</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <script defer type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </head>
  <body>
    <header>
      <!-- **** Begin Fork-Me-On-Gitlab-Ribbon-HTML. See MIT License at https://gitlab.com/seanwasere/fork-me-on-gitlab **** -->
      <a href="https://gitlab.com/lauramcastro/matched">
        <span style="position:fixed; top:40px; right:-45px; display:block; -webkit-transform: rotate(45deg); -moz-transform: rotate(45deg); background-color:green; color:white; padding: 4px 30px 4px 30px; z-index:99"><%= gettext("Fork Me On GitLab") %></span>
      </a>
      <!-- **** End Fork-Me-On-Gitlab-Ribbon-HTML **** -->
      <section class="container">
        <a href="https://www.udc.es/" class="phx-logo">
          <img src="<%= Routes.static_path(@conn, "/images/udc_logo_cor.png") %>" alt="Universidade da Coruña"/>
        </a>
        <a href="https://www.fic.udc.es/" class="phx-logo">
          <img src="<%= Routes.static_path(@conn, "/images/FIC_logo.png") %>" alt="Facultade de Informática de A Coruña"/>
        </a>
      </section>
    </header>
    <main role="main" class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= @inner_content %>
    </main>
  </body>
  <footer>
    <div style="text-align:center">
      <a href="/"><img src="<%= Routes.static_path(@conn, "/images/home.png") %>" width="25" align="middle" alt="<%= gettext("MatchED home") %>"/></a>
      <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">
        <img alt="<%= gettext("Creative Commons Licence") %>" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/4.0/80x15.png" align="middle"/></a>
    </div>
  </footer> 
</html>

lib/matched_web/templates/page/index.html.eex
<section class="phx-hero">
  <h1><%= gettext("Welcome to MatchED") %></h1>
  <p><%= gettext("Let's match some projects!") %></p>
  <div style="text-align: center">
    <%= button gettext("View judges"), to: "/judges", method: :get %>
    <%= button gettext("View projects"), to: "/projects", method: :get%>
  </div>
</section>

lib/matched_web/templates/project/index.html.eex
<h1><%= gettext("Listing projects") %></h1>

<table>
  <%= for project <- @projects do %>
  <tr>
    <td style="text-align: left"><%= render "project.html", project: project %></td>
    <td style="text-align: left"><%= button gettext("View"), to: Routes.project_path(@conn, :show, project.id), method: :get%></td>
  </tr>
  <% end %>
</table>

lib/matched_web/templates/project/project.html.eex
"<%= @project.title %>", <%= gettext("by") %> <b><%= @project.student %></b>

lib/matched_web/templates/project/show.html.eex
<h1><%= gettext("Showing project details") %></h1>
<div style="text-align: center">
<%= render "project.html", project: @project %> <%= gettext("under concentration") %>: <%= @project.concentration %>
</div>